
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer
{

using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
[MetadataType(typeof(Product_Featuers_Metadata))]
    public partial class Product_Featuers
{

    public int Product_Featuer_Id { get; set; }

    public int Product_Id { get; set; }

    public int Featuers_Id { get; set; }

    public string Value { get; set; }



    public virtual Features Features { get; set; }

    public virtual Products Products { get; set; }

}

}
